### ISSUE TITLE
Desarrollar CRUD Category

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/infusion#11]

**Comment by Duxy1996** [comment]
I want to try to do this issue by myself.  If I need help I will ask here.

**Comment by alvarocasadoc** [comment]
Te acabo de asignar la tarea. Tienes los modelos ya hechos. Échales un vistazo y si necesitas ayuda con vistas/controladores no dudes en preguntar por aquí o por Telegram 😉
