### ISSUE TITLE
Translation of hide meetup checkbox

### ISSUE THREAD

**Issue by jodoldar** [infusionvlc/infusion#95]
In the form to create a meetup, the text corresponding to the checkbox to indicate that the meetup created is going to be hidden doesn't have a translation in english.

**Comment by noloman** [comment]
Hi!

I wanted to fix this issue, but I think it's already done.
Can you please confirm it?

Thanks!

**Comment by alvarocasadoc** [comment]
Yes, @khaosdoctor already fixed it
